################################################################################
################################ INVENTORY  ####################################
################################################################################
#
# ******************************************************************************
# ENVIRONMENT:               MSS
#
# This file defines all physical hosts that are maintained within the specific
# environment along with mapping of the hosts into functional groupings.
# ******************************************************************************

all:
  vars:
  hosts:
